## Buildkite agent image version
## ref: https://hub.docker.com/r/buildkite/agent/
##
image: buildkite/agent:ubuntu-docker

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Agent docker image tag
dockerTag: 1.12.1

## Replicas Set count
replicasCount: 4

## Agent release tag, to be used just to trigger a new release of the agent
## and pull the latest docker image, as buildkite agent has no version tags yet
agentTag: "3.0"

## Agent meta-data, which can be used to assign jobs
agentMeta: "role=builder"

## Your Buildkite agent token
agentToken: "token"

## Your ssh private key
privateSshKey: "ssh_key"

## AWS credentials need to access ECR
awsCreds: " "

## Deis Workflow PaaS
## user token - client.json content encoded with base64
workflowUserToken: " "
##
## API URL
workflowApiUrl: " "

## Node selector
## comment it out if you do need to use node selector
## e.g. "role: worker-builder"
nodeSelector:
  role: worker-builder
