## elasticsearch image version
## ref: https://hub.docker.com/_/elasticsearch/
##
imageTag: 2.4.1

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## PVC storage size
storageSize: 25Gi
