## Official PostgreSQL image version
## ref: https://hub.docker.com/r/kotaimen/pgbouncer/
##
image: quay.io/clearbit/pgbouncer

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent
#
imageTag: 0.1

## PostgreSQL user
##
username: ""

## PostgreSQL password
##
password: ""

## PostgreSQL host
##
host: ""

## PostgreSQL host port
##
hostPort: 5432

## Maximum number of client connections allowed
##
maxClientConnections: 500

## How many server connections to allow per user/database pair
##
poolSize: 200

## If a server connection has been idle more than this many seconds it will be dropped.
## If 0 then timeout is disabled.
##
serverIdleTimeout: 500

## Node selector
##
## e.g. "role: worker-general"
# nodeSelector:
#   role: worker-general
